[package]
name = "sums"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "sum_bench"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.6.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
